2021-12-21 15:07:40,106 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff796b2bf40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:07:40,111 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff796b2bbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:08:49,174 INFO server Dash is running on http://127.0.0.1:8050/

2021-12-21 15:08:51,379 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc3bec92e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:08:51,384 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc4f75bd00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:11:20,090 INFO server Dash is running on http://127.0.0.1:8050/

2021-12-21 15:11:30,705 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2cb016d040>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:11:30,717 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2cb0113160>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:11:46,942 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2cb091f340>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:11:46,950 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2cb00c65b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:14:14,476 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd6265130>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:14:14,482 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcdd5a02280>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:21:09,352 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4dbf7eee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:21:09,360 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4dbf6d9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:21:57,150 INFO server Dash is running on http://127.0.0.1:8050/

2021-12-21 15:21:59,725 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7f2fa35b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:21:59,730 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7f2fa3b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:22:05,480 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7f2e80d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:22:05,488 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7dbd07b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:23:23,458 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3244df9fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:23:23,464 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f32445c42b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:23:23,916 ERROR app inscritos_cidade_choropleth: list indices must be integers or slices, not str
2021-12-21 15:23:30,114 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe48dd57160>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:23:30,122 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe48fdb8940>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:23:30,537 ERROR app inscritos_regiao_choropleth: list indices must be integers or slices, not str
2021-12-21 15:23:41,904 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efef96b8f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:23:41,914 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efef96ade50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:23:42,387 ERROR app inscritos_regiao_choropleth: list indices must be integers or slices, not str
2021-12-21 15:23:47,826 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6cdc30d0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:23:47,832 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6cdc283a00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:23:48,284 ERROR app inscritos_regiao_choropleth: list indices must be integers or slices, not str
2021-12-21 15:23:56,054 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f102971b040>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:23:56,074 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f102971b7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:23:56,437 ERROR app inscritos_regiao_choropleth: list indices must be integers or slices, not str
2021-12-21 15:23:59,183 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9f58b2220>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:23:59,197 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9f58d8a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:23:59,712 ERROR app inscritos_regiao_choropleth: list indices must be integers or slices, not str
2021-12-21 15:24:02,132 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eb841d1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:24:02,141 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0eb8429820>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:24:02,532 ERROR app inscritos_regiao_choropleth: list indices must be integers or slices, not str
2021-12-21 15:26:20,077 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb65df9c4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:26:20,097 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb65e7f3730>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:26:20,566 ERROR app inscritos_regiao_choropleth: list indices must be integers or slices, not str
2021-12-21 15:28:51,340 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faded4d6fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:28:51,352 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fadec523790>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:28:51,727 ERROR app inscritos_regiao_choropleth: list indices must be integers or slices, not str
2021-12-21 15:28:53,044 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fadec4affa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:28:53,049 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fade4bb8e20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:28:53,370 ERROR app inscritos_regiao_choropleth: list indices must be integers or slices, not str
2021-12-21 15:33:29,190 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fadec3811f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:33:29,194 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fadec0f04c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:33:29,658 ERROR app inscritos_regiao_choropleth: list indices must be integers or slices, not str
2021-12-21 15:36:57,043 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fadec5160d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:36:57,052 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fade4b88550>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 15:36:57,374 ERROR app inscritos_regiao_choropleth: list indices must be integers or slices, not str
2021-12-21 15:54:11,807 INFO server Dash is running on http://127.0.0.1:8050/

2021-12-21 15:54:59,302 ERROR app fig_inscritos_iniciativa: String or int arguments are only possible when a DataFrame or an array is provided in the `data_frame` argument. No DataFrame was provided, but argument 'color' is of type str or int.
2021-12-21 15:54:59,775 ERROR app inscritos_regiao_choropleth: 'inscritos'
2021-12-21 15:59:58,027 ERROR app fig_inscritos_categoria: Invalid value
2021-12-21 15:59:58,306 INFO app Fig periodo carregado com sucesso
2021-12-21 15:59:58,676 INFO app Choropleth cidade carregado com sucesso
2021-12-21 16:00:43,282 ERROR app fig_inscritos_iniciativa: String or int arguments are only possible when a DataFrame or an array is provided in the `data_frame` argument. No DataFrame was provided, but argument 'color' is of type str or int.
2021-12-21 16:00:43,577 INFO app Fig periodo carregado com sucesso
2021-12-21 16:00:43,843 INFO app Fig categoria carregado com sucesso
2021-12-21 16:00:44,015 INFO app Fig regiao carregado com sucesso
2021-12-21 16:00:44,308 INFO app Choropleth cidade carregado com sucesso
2021-12-21 16:00:44,675 ERROR app inscritos_regiao_choropleth: 'inscritos'
2021-12-21 16:00:46,194 ERROR app fig_inscritos_iniciativa: String or int arguments are only possible when a DataFrame or an array is provided in the `data_frame` argument. No DataFrame was provided, but argument 'color' is of type str or int.
2021-12-21 16:00:57,916 ERROR app inscritos_regiao_choropleth: 'inscritos'
2021-12-21 16:00:58,127 INFO app Fig regiao carregado com sucesso
2021-12-21 16:04:18,642 INFO app Fig periodo carregado com sucesso
2021-12-21 16:04:18,645 INFO app Fig categoria carregado com sucesso
2021-12-21 16:04:19,055 INFO app Choropleth cidade carregado com sucesso
2021-12-21 16:04:36,625 INFO app requisição da iniciativa feita com sucesso
2021-12-21 16:04:36,982 INFO app requisição da categoria feita com sucesso
2021-12-21 16:04:48,014 INFO app Fig iniciativa carregado com sucesso
2021-12-21 16:04:48,479 ERROR app inscritos_regiao_choropleth: 'inscritos'
2021-12-21 16:04:48,751 INFO app Fig regiao carregado com sucesso
2021-12-21 16:07:21,585 INFO app Fig categoria carregado com sucesso
2021-12-21 16:07:21,587 INFO app Fig periodo carregado com sucesso
2021-12-21 16:07:21,959 INFO app Choropleth cidade carregado com sucesso
2021-12-21 16:07:50,427 INFO app requisição da iniciativa feita com sucesso
2021-12-21 16:07:51,083 INFO app requisição da categoria feita com sucesso
2021-12-21 16:08:15,487 INFO app Fig regiao carregado com sucesso
2021-12-21 16:08:15,701 ERROR app inscritos_regiao_choropleth: 'inscritos'
2021-12-21 16:08:16,253 ERROR app fig_inscritos_iniciativa: String or int arguments are only possible when a DataFrame or an array is provided in the `data_frame` argument. No DataFrame was provided, but argument 'color' is of type str or int.
2021-12-21 16:08:55,038 INFO app Fig categoria carregado com sucesso
2021-12-21 16:08:55,040 INFO app Fig periodo carregado com sucesso
2021-12-21 16:08:55,451 INFO app Choropleth cidade carregado com sucesso
2021-12-21 16:09:13,025 INFO app requisição da iniciativa feita com sucesso
2021-12-21 16:09:13,390 INFO app requisição da categoria feita com sucesso
2021-12-21 16:09:25,008 ERROR app fig_inscritos_iniciativa: 'str' object has no attribute 'copy'
2021-12-21 16:09:25,499 ERROR app inscritos_regiao_choropleth: 'inscritos'
2021-12-21 16:09:25,713 INFO app Fig regiao carregado com sucesso
2021-12-21 16:11:42,897 INFO app Fig categoria carregado com sucesso
2021-12-21 16:11:42,901 INFO app Fig periodo carregado com sucesso
2021-12-21 16:11:43,249 INFO app Choropleth cidade carregado com sucesso
2021-12-21 16:12:10,386 INFO app requisição da iniciativa feita com sucesso
2021-12-21 16:12:10,953 INFO app requisição da categoria feita com sucesso
2021-12-21 16:12:32,359 ERROR app fig_inscritos_iniciativa: 'str' object has no attribute 'copy'
2021-12-21 16:12:33,329 INFO app Fig regiao carregado com sucesso
2021-12-21 16:12:33,999 ERROR app inscritos_regiao_choropleth: 'inscritos'
2021-12-21 16:13:16,100 INFO app Fig periodo carregado com sucesso
2021-12-21 16:13:16,105 INFO app Fig categoria carregado com sucesso
2021-12-21 16:13:16,477 INFO app Choropleth cidade carregado com sucesso
2021-12-21 16:13:30,460 INFO app requisição da iniciativa feita com sucesso
2021-12-21 16:13:34,054 INFO app requisição da categoria feita com sucesso
2021-12-21 16:13:44,425 ERROR app fig_inscritos_iniciativa: 'str' object has no attribute 'copy'
2021-12-21 16:13:45,202 INFO app Fig regiao carregado com sucesso
2021-12-21 16:13:45,516 ERROR app inscritos_regiao_choropleth: 'inscritos'
2021-12-21 16:14:56,693 INFO app Fig periodo carregado com sucesso
2021-12-21 16:14:56,709 INFO app Fig categoria carregado com sucesso
2021-12-21 16:14:57,124 INFO app Choropleth cidade carregado com sucesso
2021-12-21 16:15:17,010 INFO app requisição da iniciativa feita com sucesso
2021-12-21 16:15:17,472 INFO app requisição da categoria feita com sucesso
2021-12-21 16:15:30,867 ERROR app fig_inscritos_iniciativa: 'str' object has no attribute 'copy'
2021-12-21 16:15:48,314 INFO server Dash is running on http://127.0.0.1:8050/

2021-12-21 16:15:50,975 INFO app Fig categoria carregado com sucesso
2021-12-21 16:15:50,976 INFO app Fig periodo carregado com sucesso
2021-12-21 16:15:51,372 INFO app Choropleth cidade carregado com sucesso
2021-12-21 16:16:08,736 INFO app requisição da iniciativa feita com sucesso
2021-12-21 16:16:09,309 INFO app requisição da categoria feita com sucesso
2021-12-21 16:16:19,247 ERROR app fig_inscritos_iniciativa: 'str' object has no attribute 'copy'
2021-12-21 16:16:20,341 ERROR app inscritos_regiao_choropleth: 'inscritos'
2021-12-21 16:16:20,439 INFO app Fig regiao carregado com sucesso
2021-12-21 16:16:56,714 INFO app Fig categoria carregado com sucesso
2021-12-21 16:16:56,716 INFO app Fig periodo carregado com sucesso
2021-12-21 16:16:57,161 INFO app Choropleth cidade carregado com sucesso
2021-12-21 16:17:14,592 INFO app requisição da iniciativa feita com sucesso
2021-12-21 16:17:15,013 INFO app requisição da categoria feita com sucesso
2021-12-21 16:17:22,322 INFO server Dash is running on http://127.0.0.1:8050/

2021-12-21 16:17:24,261 INFO app Fig periodo carregado com sucesso
2021-12-21 16:17:24,472 INFO app Fig categoria carregado com sucesso
2021-12-21 16:17:28,047 INFO app Fig periodo carregado com sucesso
2021-12-21 16:17:28,095 INFO app Fig categoria carregado com sucesso
2021-12-21 16:17:28,464 INFO app Choropleth cidade carregado com sucesso
2021-12-21 16:21:19,822 INFO app requisição da iniciativa feita com sucesso
2021-12-21 16:21:19,879 INFO app Fig categoria carregado com sucesso
2021-12-21 16:21:20,008 INFO app requisição da iniciativa feita com sucesso
2021-12-21 16:21:21,050 INFO app Fig periodo carregado com sucesso
2021-12-21 16:21:55,763 INFO server Dash is running on http://127.0.0.1:8050/

2021-12-21 16:24:38,698 INFO app Fig periodo carregado com sucesso
2021-12-21 16:25:39,732 ERROR app request iniciativas: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2021-12-21 16:25:39,752 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faec9ecf0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 16:25:40,088 ERROR app inscritos_regiao_choropleth: list indices must be integers or slices, not str
2021-12-21 16:25:40,473 INFO app Choropleth cidade carregado com sucesso
2021-12-21 16:28:01,559 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffb859a7c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 16:28:01,574 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffb840b1970>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-21 16:28:01,959 ERROR app inscritos_regiao_choropleth: list indices must be integers or slices, not str
2021-12-21 16:28:02,399 INFO app Choropleth cidade carregado com sucesso
2021-12-22 11:26:36,037 INFO server Dash is running on http://127.0.0.1:8050/

2021-12-22 11:27:32,300 INFO app Fig periodo carregado com sucesso
2021-12-22 11:27:32,302 INFO app Fig categoria carregado com sucesso
2021-12-22 11:27:32,854 INFO app Choropleth cidade carregado com sucesso
2021-12-22 11:27:46,494 INFO app requisição da iniciativa feita com sucesso
2021-12-22 11:27:46,941 INFO app requisição da categoria feita com sucesso
2021-12-22 11:27:57,080 INFO app Fig iniciativa carregado com sucesso
2021-12-22 11:27:57,392 INFO app Fig regiao carregado com sucesso
2021-12-22 11:27:57,606 ERROR app inscritos_regiao_choropleth: 'inscritos'
2021-12-22 11:30:40,306 INFO server Dash is running on http://127.0.0.1:8050/

2021-12-22 11:30:42,583 INFO app Fig periodo carregado com sucesso
2021-12-22 11:30:42,587 INFO app Fig categoria carregado com sucesso
2021-12-22 11:30:42,958 INFO app Choropleth cidade carregado com sucesso
2021-12-22 11:31:01,891 INFO app requisição da iniciativa feita com sucesso
2021-12-22 11:31:02,345 INFO app requisição da categoria feita com sucesso
2021-12-22 11:31:12,439 INFO app Fig regiao carregado com sucesso
2021-12-22 11:31:12,712 INFO app Fig iniciativa carregado com sucesso
2021-12-22 11:31:13,033 ERROR app inscritos_regiao_choropleth: 'inscritos'
2021-12-22 11:31:32,182 ERROR app fig_inscritos_categoria: Invalid value
2021-12-22 11:31:32,573 INFO app Fig periodo carregado com sucesso
2021-12-22 11:31:33,024 INFO app Choropleth cidade carregado com sucesso
2021-12-22 11:31:51,636 INFO app requisição da iniciativa feita com sucesso
2021-12-22 11:31:51,909 INFO app requisição da categoria feita com sucesso
2021-12-22 11:32:02,143 INFO app Fig iniciativa carregado com sucesso
2021-12-22 11:32:02,514 INFO app Fig regiao carregado com sucesso
2021-12-22 11:32:02,771 ERROR app inscritos_regiao_choropleth: 'inscritos'
2021-12-22 11:38:05,879 INFO app Fig periodo carregado com sucesso
2021-12-22 11:38:05,883 INFO app Fig categoria carregado com sucesso
2021-12-22 11:38:06,315 INFO app Choropleth cidade carregado com sucesso
2021-12-22 11:38:23,044 INFO app requisição da iniciativa feita com sucesso
2021-12-22 11:38:30,107 INFO app requisição da categoria feita com sucesso
2021-12-22 11:38:45,827 INFO app Fig iniciativa carregado com sucesso
2021-12-22 11:38:46,221 INFO app Fig regiao carregado com sucesso
2021-12-22 11:38:46,459 ERROR app inscritos_regiao_choropleth: 'inscritos'
2021-12-22 11:39:05,157 ERROR app fig_inscritos_periodo: Invalid value
2021-12-22 11:39:05,514 INFO app Fig categoria carregado com sucesso
2021-12-22 11:39:05,861 INFO app Choropleth cidade carregado com sucesso
2021-12-22 11:39:10,240 INFO app Fig categoria carregado com sucesso
2021-12-22 11:39:10,244 INFO app Fig periodo carregado com sucesso
2021-12-22 11:39:10,731 INFO app Choropleth cidade carregado com sucesso
2021-12-22 11:39:14,127 ERROR app fig_inscritos_periodo: Invalid value
2021-12-22 11:39:16,233 INFO app Choropleth cidade carregado com sucesso
2021-12-22 11:39:17,227 INFO app Fig periodo carregado com sucesso
2021-12-22 11:39:17,230 INFO app Fig categoria carregado com sucesso
2021-12-22 11:39:17,535 INFO app Choropleth cidade carregado com sucesso
2021-12-22 11:40:12,368 INFO server Dash is running on http://127.0.0.1:8050/

2021-12-22 11:44:14,514 INFO server Dash is running on http://127.0.0.1:8050/

2021-12-22 11:45:03,877 ERROR app request iniciativas: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2021-12-22 11:45:03,884 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4420175640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-22 11:45:04,346 ERROR app inscritos_regiao_choropleth: list indices must be integers or slices, not str
2021-12-22 11:45:09,135 INFO app Choropleth cidade carregado com sucesso
2021-12-22 11:51:13,007 INFO app Fig periodo carregado com sucesso
2021-12-22 11:51:13,014 INFO app Fig categoria carregado com sucesso
2021-12-22 11:51:13,393 INFO app Choropleth cidade carregado com sucesso
2021-12-22 11:51:32,607 INFO app requisição da iniciativa feita com sucesso
2021-12-22 11:51:32,750 INFO app requisição da categoria feita com sucesso
2021-12-22 11:51:42,895 ERROR app inscritos_regiao_choropleth: 'inscritos'
2021-12-22 11:51:43,454 INFO app Fig iniciativa carregado com sucesso
2021-12-22 11:51:43,652 INFO app Fig regiao carregado com sucesso
2021-12-22 11:52:36,201 INFO server Dash is running on http://127.0.0.1:8050/

2021-12-22 11:52:40,091 INFO app Fig categoria carregado com sucesso
2021-12-22 11:52:40,094 INFO app Fig periodo carregado com sucesso
2021-12-22 11:52:40,442 INFO app Choropleth cidade carregado com sucesso
2021-12-22 11:52:58,845 INFO app requisição da iniciativa feita com sucesso
2021-12-22 11:52:59,168 INFO app requisição da categoria feita com sucesso
2021-12-22 11:53:09,200 INFO app Fig iniciativa carregado com sucesso
2021-12-22 11:53:09,534 ERROR app inscritos_regiao_choropleth: 'inscritos'
2021-12-22 11:53:09,763 INFO app Fig regiao carregado com sucesso
2021-12-22 11:53:49,253 INFO app Fig periodo carregado com sucesso
2021-12-22 11:53:49,254 INFO app Fig categoria carregado com sucesso
2021-12-22 11:53:49,613 INFO app Choropleth cidade carregado com sucesso
2021-12-22 11:53:54,935 INFO app Fig categoria carregado com sucesso
2021-12-22 11:53:54,936 INFO app Fig periodo carregado com sucesso
2021-12-22 11:53:55,340 INFO app Choropleth cidade carregado com sucesso
2021-12-22 11:55:50,157 INFO server Dash is running on http://127.0.0.1:8050/

2021-12-22 11:58:04,839 ERROR app request iniciativas: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2021-12-22 11:58:04,876 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4914283f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-22 11:58:05,290 ERROR app inscritos_regiao_choropleth: list indices must be integers or slices, not str
2021-12-22 11:58:05,744 INFO app Choropleth cidade carregado com sucesso
2021-12-22 15:07:46,593 INFO app Fig categoria carregado com sucesso
2021-12-22 15:07:46,598 INFO app Fig periodo carregado com sucesso
2021-12-22 15:07:47,024 INFO app Choropleth cidade carregado com sucesso
2021-12-22 15:08:06,937 INFO app requisição da iniciativa feita com sucesso
2021-12-22 15:08:07,034 INFO app requisição da categoria feita com sucesso
2021-12-22 15:08:16,791 INFO app Fig iniciativa carregado com sucesso
2021-12-22 15:08:17,484 INFO app Fig regiao carregado com sucesso
2021-12-22 15:08:17,787 ERROR app inscritos_regiao_choropleth: 'inscritos'
2021-12-22 15:17:27,265 INFO server Dash is running on http://127.0.0.1:8050/

2021-12-22 15:17:28,792 INFO app Fig categoria carregado com sucesso
2021-12-22 15:17:28,796 INFO app Fig periodo carregado com sucesso
2021-12-22 15:17:29,233 INFO app Choropleth cidade carregado com sucesso
2021-12-22 15:17:46,160 INFO app requisição da iniciativa feita com sucesso
2021-12-22 15:17:48,165 INFO app requisição da categoria feita com sucesso
2021-12-22 15:17:57,800 INFO app Fig iniciativa carregado com sucesso
2021-12-22 15:17:58,398 ERROR app inscritos_regiao_choropleth: 'inscritos'
2021-12-22 15:17:58,896 INFO app Fig regiao carregado com sucesso
2021-12-22 15:21:44,371 INFO app Fig periodo carregado com sucesso
2021-12-22 15:21:44,373 INFO app Fig categoria carregado com sucesso
2021-12-22 15:21:44,762 INFO app Choropleth cidade carregado com sucesso
2021-12-22 15:22:06,183 INFO app Fig periodo carregado com sucesso
2021-12-22 15:22:06,185 INFO app Fig categoria carregado com sucesso
2021-12-22 15:22:49,786 INFO app Choropleth cidade carregado com sucesso
2021-12-22 15:25:00,023 INFO server Dash is running on http://127.0.0.1:8050/

2021-12-22 15:28:15,704 INFO server Dash is running on http://127.0.0.1:8050/

2021-12-22 15:31:25,680 ERROR app request iniciativas: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2021-12-22 15:31:25,713 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa3803d4e20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-22 15:31:26,051 ERROR app inscritos_regiao_choropleth: list indices must be integers or slices, not str
2021-12-22 15:31:26,824 INFO app Choropleth cidade carregado com sucesso
2021-12-22 15:39:10,533 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f786d1d4df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-22 15:39:10,539 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f786c152a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-22 15:39:11,204 INFO app Choropleth cidade carregado com sucesso
2021-12-22 16:23:27,961 ERROR app request iniciativas: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/iniciativas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78574ebeb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-22 16:23:27,972 ERROR app request categorias: HTTPConnectionPool(host='api-ssa.ced.seduc', port=5057): Max retries exceeded with url: /v1.0/filtros/categorias (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78577e6d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-12-22 16:23:28,429 INFO app Choropleth cidade carregado com sucesso
